kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      serviceAccountName: projectlister
      containers:
      - name: front
        image: telliottio/front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - name: http
    targetPort: 80
    port: 80
