---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front
  namespace: front
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: telliott.io
    http:
      paths:
      - path: /
        backend:
          serviceName: front
          servicePort: http