apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- ingress.yaml
- cloudprober.yaml
images:
- name: front
  newName: telliottio/front
  newTag: v0.1.10
