apiVersion: v1
kind: ServiceAccount
metadata:
  name: projectlister
  namespace: front
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: project-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-reader
  # Namespace in which the role applies
  # In this case, the namespace we want to be able to read
  namespace: projectlist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-reader
subjects:
- kind: ServiceAccount
  name: projectlister
  # Namespace of the service account
  namespace: front