apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- ingress.yaml
- cloudprober.yaml
configMapGenerator:
- files:
  - context=kubecontext.txt
  name: kubeenv
  namespace: front
images:
- name: front
  newName: telliottio/front
  newTag: latest
