name: 'Release'
on:
  push:
      tags:
        - v* # Run only on version tags
jobs:
  deploy:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Static files
        run: |
            mkdir -p build
            cp -r public build/public 
            cp -r views build/views
      - name: run
        uses: cedrickring/golang-action@1.5.1
        with:
          args: GOOS=linux GOARCH=amd64 go build -o build/front ./cmd/front
      - name: Build & Push Container
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: build
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "telliottio/front"
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
          LATEST: "false"
